### ISSUE TITLE
Switch docs to use docs.rs

### ISSUE THREAD

**Issue by robinst** [trishume/syntect#110]
Before I raise any PRs, I was wondering if you're ok with switching the docs to use docs.rs instead of hosting them yourself. That has a couple of advantages:

* It makes the build simpler (we can just remove that step)
* It means the docs are available for older versions as well
* We can add a badge for it

There's disadvantages as well:

* It's run by someone other than you :). But given that so many crates use it (including crates by the rust-lang team), the Rust community has a pretty big interest in keeping the site up.

You can check out the docs here: https://docs.rs/syntect/

**Comment by trishume** [comment]
Yah I totally agree with this, the main reason it isn't already done is I'm lazy and the existing docs work. If you submit a PR to switch it to docs.rs and delete the docs publishing travis hook thingy I'd definitely accept it.
