### ISSUE TITLE
Use native rust regex?

### ISSUE THREAD

**Issue by TyOverby** [trishume/syntect#12]
Having a dependency on a cmake and a C compiler makes it hard to use this project due to the dependency libonig.  Would it be possible to switch over to the [official rust regex package](https://github.com/rust-lang-nursery/regex)?

**Comment by trishume** [comment]
No, because Sublime syntaxes use all sorts of fancy features like back-references. It might be possible to switch to fancy-regex from the pulldown-cmark repo with some extra work on that library though. That library isn't quite good enough yet but it might be with a bit of work.

**Comment by TyOverby** [comment]
Oh interesting, I expected some missing feature to be the reason that you didn't use the official rust regex crate.  

Fancy-regex looks interesting, they even mention sublime-text syntax files as being a use case.  Are they using it to highlight source files as well?

**Comment by trishume** [comment]
It was written by the author of https://github.com/google/xi-editor in anticipation of him writing a highlighter for Sublime Text syntax files, I just got to it first. It's currently mostly but not completely finished, and not used by anything as far as I know.

**Comment by DemiMarie** [comment]
@trishume The `regex` crate could still be used (and be a performance win) on regexps that it supports.

**Comment by anowell** [comment]
+1. I was experimenting with syntect in a project targeting emscripten (basically using syntect in the browser as an alternative to highlight.js), but it chokes on building `onig_sys`.

**Comment by trishume** [comment]
@anowell I seem to remember that the `regex` crate also doesn't work with emscripten yet, so that wouldn't be much help. Has that changed? Or possibly am I misremembering this and it has always worked with emscripten?

**Comment by anowell** [comment]
Looks like it should work as of `regex` 0.2 (see https://github.com/rust-lang/regex/issues/307). I just tried a very basic match to confirm and had success. 

`fancy-regex` on the other hand currently leverages `regex = "0.1.63"` for its NFA regex instructions (and panics accordingly for the same basic match), so at the very least, it'd take bumping the regex dependency there to target emscripten.

**Comment by kornelski** [comment]
It'd be great to have a better regex library. I've been getting segfaults in Oniguruma.

**Comment by trishume** [comment]
See #34, work on this has stalled since I'm busy/interested in other things. I still maintain syntect but don't actively work on new features myself anymore. But if someone else volunteers to work on getting #34 up to date and high quality then I'm happy to mentor and code review.

**Comment by Enselic** [comment]
This issue can be closed with the motivation:

Fixed in https://github.com/trishume/syntect/releases/tag/v4.0.0

(Maybe someone with Collaborator privileges can help me clean the syntect issue inbox? This is one of many cleanup actions we can take. I will happily point out more if someone is interested in helping me out.)
