### ISSUE TITLE
[linux] error while loading shared libraries: libonig.so

### ISSUE THREAD

**Issue by TyOverby** [trishume/syntect#13]
Running "cargo run" on a basic project with syntect yields the following error:

```
target/debug/eta: error while loading shared libraries: libonig.so: cannot open shared object file: No such file or directory
```

I tried running 

```
$ export LD_LIBRARY_PATH="./target/debug/build/onig_sys-*/out/lib/"
```

as it is suggested in the readme, but that doesn't help either.

**Comment by trishume** [comment]
Hmmm, do glob stars in strings in exports work properly? I'm not sure they do.
Maybe try something more like the code used for travis here: https://github.com/trishume/syntect/blob/master/.travis.yml#L15

**Comment by TyOverby** [comment]
Oh yep, that's the issue.  Would it be possible to statically compile against libonig so that this issue doesn't crop up?

**Comment by trishume** [comment]
Perhaps, that would be nice, perhaps you should file an issue against https://github.com/rust-onig/rust-onig

**Comment by TyOverby** [comment]
https://github.com/rust-onig/rust-onig/issues/16
