### ISSUE TITLE
Getting output for terminal

### ISSUE THREAD

**Issue by leshow** [trishume/syntect#131]
I've been browsing through the examples & docs and I'm very glad to see this library exists!

I'm making a markdown previewer for the terminal. During codeblocks I have information (usually) about the language and a string reference for the code that I need to highlight, I need to output it colored for your average 24-bit terminal. I got this so far:

```rust
    fn highlight_lines(&self, s: &str, buf: &mut String) {
        let ts = ThemeSet::load_defaults();
        let ps = SyntaxSet::load_defaults_nonewlines();

        let syntax = if let Some(ref lang) = self.lang {
            ps.find_syntax_by_name(lang)
        } else {
            ps.find_syntax_by_first_line(s)
        }.unwrap_or_else(|| ps.find_syntax_plain_text());

        let mut h = HighlightLines::new(syntax, &ts.themes["base16-ocean.dark"]);
        for line in s.lines() {
            let ranges: Vec<(Style, &str)> = h.highlight(line);
            let escaped = as_24_bit_terminal_escaped(&ranges[..], false);
            buf.push_str(&escaped);
        }
    }
```

This function takes close to 10 seconds to run (it gets executed twice on short strings) and doesn't colour the output at all. I was hoping you could point me in the direction of what I'm doing incorrectly.

So long as I select one of the 'default' themes, I don't need to actually have a theme file locally right?

**Comment by cmyr** [comment]
@leshow Are you sure you're finding a syntax? Are you sure you're getting a theme? Looking at the `examples/syncat.rs`, there is a theme loading step you may be missing... Default themes _are_ included, but are loaded lazily.

**Comment by leshow** [comment]
It seems to always end up with a Plain Text syntax struct, however my test file has multiple different languages in it and `find_syntax_by_name` is being called with `sh`, `js`, `rust`.

**Comment by cmyr** [comment]
@leshow I think you want `find_syntax_by_extension` in that case. "Names" iirc are the names in the sublime-syntax defs; 'Rust', 'JavaScript', 'HTML (Rails)' etc.

**Comment by leshow** [comment]
Thanks for the tip that gets me some output at least. Do you know if the themes are cross platform? I'm on linux, the output of the highlighting looks pretty weird.


![markdown](https://user-images.githubusercontent.com/1128302/34739521-90645eb0-f54a-11e7-8e2b-f5a733505cde.png)

Ever seen anything like this before?

Would you be interested in a documentation PR for drawing to terminal after I figure it out?

**Comment by cmyr** [comment]
@leshow themes are cross platform, but your terminal may not support 24 bit color? Although I suspect something else is going on. Try running the syncat example, and see if it renders correctly. Otherwise I'm not totally sure what's up.

I can't answer the second question, because I'm not a maintainer, just a distracted person who gets notifications for this repo. ;)

**Comment by leshow** [comment]
Haha well my lucky day, thanks for your help!
