### ISSUE TITLE
Add support for Elixir

### ISSUE THREAD

**Issue by bennyyip** [trishume/syntect#134]
Syntect is great!
But it lacks support for Elixir. I found an official TextMate bundle for elixir(https://github.com/elixir-editors/elixir-tmbundle), which may be helpful.

**Comment by Keats** [comment]
I believe no additional syntaxes will be added to the default syntect syntaxes set, ask whichever tool that is using syntect to add it to their syntaxes

**Comment by trishume** [comment]
I'm open to adding a set of bonus syntaxes at some point as a Cargo feature, especially if someone PR'd it.

**Comment by yonkeltron** [comment]
Is this still the case that no new languages will be added to the default set?

**Comment by trishume** [comment]
See #168. The status is that I'm not going to do it, but if someone contributes a cargo feature which optionally bundles an extended set of syntaxes I'll accept it, especially if it's based on one of the existing curated syntax sets from bat, Zola or sourcegraph.

**Comment by Enselic** [comment]
Since we will not add this syntax on its own so to speak, let's close this issue and use #168 for tracking and discussion on adding additional syntaxes.
