### ISSUE TITLE
SyntaxSet isn't Send and Sync

### ISSUE THREAD

**Issue by bjorn3** [trishume/syntect#188]
This makes it impossible to store it in a `lazy_static!`, which I need because of the slow creation of `SyntaxSet`. I currently workaround this using `thread_local!`, which is harder to use due to having a scoped api.

**Comment by robinst** [comment]
Hey! I'm currently working on that, see #182.

**Comment by bjorn3** [comment]
Didn't know about that PR.

**Comment by robinst** [comment]
Since 3.0.0 `SyntaxSet` is both `Send` and `Sync` 🎉: https://github.com/trishume/syntect/blob/master/CHANGELOG.md#version-30

**Comment by bjorn3** [comment]
Hooray
