### ISSUE TITLE
Wonkiness in rust code with noise á la git conflict markers

### ISSUE THREAD

**Issue by jansol** [trishume/syntect#208]
I recently came across a case where the decimal point would spontaneously vanish from view in xi after a git conflict marker. Turns out this shows up as an error in syncat as well. Minimal code to reproduce:
```
fn main() {
    let a;
<
    let foo = 3.14;
}
```

**Comment by cmyr** [comment]
the rust grammar is indicating that the decimal point is a syntax error. here's a screenshot showing xi and syncat:
![0luakgqq](https://user-images.githubusercontent.com/3330916/45597869-595d6900-b9a0-11e8-8000-013cb6c3ae41.png)

**Comment by trishume** [comment]
This is not a bug in syntect, outputting `invalid.illegal` is just something some of the Sublime grammars do when they know some syntax is borked. Then themes tend to colour that with a red background.

See this screenshot of Sublime doing the exact same thing:
<img width="248" alt="screen shot 2018-09-16 at 9 46 13 am" src="https://user-images.githubusercontent.com/887610/45598731-88baa880-b995-11e8-9c8d-e6851a857bd1.png">

**Comment by trishume** [comment]
If you really don't like this and it's causing problems you can try submitting a patch to the Rust grammar in the Sublime packages repo.
