### ISSUE TITLE
Elm syntax does not compile on master anymore

### ISSUE THREAD

**Issue by Keats** [trishume/syntect#211]
The syntaxes are located at https://github.com/elm-community/SublimeElmLanguageSupport/tree/master/Syntaxes . I added the repo to the packages folder of master for trying it quickly.

Error message while running `make packs` in syntect master

```bash
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ParseSyntax(RegexCompileError("$+(?!^ {4})", Error(-114, target of repeat operator is invalid)), Some("testdata/Packages/SublimeElmLanguageSupport/Syntaxes/Elm Compile Messages.sublime-syntax"))', libcore/result.rs:1009:5
```

Offending line: https://github.com/elm-community/SublimeElmLanguageSupport/blob/master/Syntaxes/Elm%20Compile%20Messages.sublime-syntax#L67

**Comment by keith-hall** [comment]
I wonder if this is related to the regex rewriting for no newlines mode, as it seems to be converting the `\n` to `$`, and as it is followed by a `+`, it's seen as invalid by Oniguruma.

**Comment by robinst** [comment]
Yeah looks like nonewlines mode. We could tweak the `\n` to `$` rewriting some more, but fixing the grammar would also be good.

Looks like the line to tweak for the rewriting is here: https://github.com/trishume/syntect/blob/master/src/parsing/yaml_load.rs#L561

**Comment by Keats** [comment]
So the line in the grammar should be `match: '(?!^ {4})'` ?

**Comment by trishume** [comment]
Can someone confirm the syntax compiles now that the fix is merged?

**Comment by Keats** [comment]
It does work
