### ISSUE TITLE
Request: Consider releasing binaries

### ISSUE THREAD

**Issue by jan-auer** [trishume/syntect#214]
The example in this project would be a perfect replacement for interpreter-based command line utilities like rougify or pygmentize, especially since it requires no runtime dependencies. It would be great if the crate could expose a binary so it can be installed with `cargo install`. 

As a next step, it would be cool to build those binaries and upload them to GitHub releases and optionally add a homebrew cask for it.

**Comment by keith-hall** [comment]
you're referring to `syncat`? have you considered using https://github.com/sharkdp/bat instead from https://github.com/trishume/syntect/blob/731bdaede42ff0f4d9aebd7587241e53b4bba11a/Readme.md#projects-using-syntect?

**Comment by jan-auer** [comment]
Totally missed that, when looking at that section in the readme, sorry about that! Bat is exactly what I was looking for, going to close this issue. Thanks a bunch!
