### ISSUE TITLE
Document SyntaxReference and highlighted_html_for_string

### ISSUE THREAD

**Issue by David-OConnor** [trishume/syntect#227]
There's no mention of highlighted_html_for_string usage in the examples, or anywhere I've found outside the API docs. There's an example of highlighted_html_for_file, but this doesn't require a SyntaxReference param, which there's no example of either.

**Comment by trishume** [comment]
Indeed, might be nice to have an example. In the mean time look at the `SyntaxSet` docs for how to get a `SyntaxReference`, there's an example of getting one in the `easy::HighlightLines` docs.

**Comment by David-OConnor** [comment]
Are you referring to this? https://docs.rs/syntect/3.0.2/syntect/easy/struct.HighlightLines.html

This is SyntaxSet and ThemeSet, but no SyntaxReference

**Comment by trishume** [comment]
```rust
et ps = SyntaxSet::load_defaults_newlines();
let ts = ThemeSet::load_defaults();

let syntax = ps.find_syntax_by_extension("rs").unwrap();
```

Here `syntax` is a `SyntaxReference`

**Comment by David-OConnor** [comment]
Thanks; sorted!

**Comment by Enselic** [comment]
Good to hear your question was answered.

Documentation can always be improved, but I don't think it's worth keeping this issue open for it in this case.
