### ISSUE TITLE
Why is color never un-set in as_24_bit_terminal_escaped?

### ISSUE THREAD

**Issue by bjorn3** [trishume/syntect#233]
https://github.com/trishume/syntect/blob/688e17e003c071b44ea499438962a8573c8384a8/src/util.rs#L38

**Comment by trishume** [comment]
I think so that the blank space past the end of the line in the terminal will also have the background color. Also more efficient I guess. If you're making a tool that wants the color un-set after you can just print that sequence yourself.

**Comment by bjorn3** [comment]
Get it.
