### ISSUE TITLE
Splitting `\t`s in HighlightLines::highlight()?

### ISSUE THREAD

**Issue by slmjkdbtl** [trishume/syntect#238]
I'm trying to visualize tabs, and it would be much easier to go with
```rust
for (style, word) in h.highlight(line, &ps) {
    if word == '\t' {
        // do tab stuff
    } else {
        // render normal text
    }
}
```
it's totally possible to construct a new collection with tabs split, but this would just be easier. (would love to know better ways to deal with tabs)

**Comment by trishume** [comment]
You might find the `util::split_at` function useful, also maybe check out the source for the `util::modify_range` function.

**Comment by slmjkdbtl** [comment]
Thanks, I've managed to deal with tabs now. Another quick question, I'm now highlighting visible lines every frame, but sometimes the highlighting loses context once certain lines are no longer passed, e.g.
```rust
struct Test {
    a: i32,
}
```
when I scroll to 
```rust
    a: i32,
}
```
it loses highlight. What should I use if I want to correctly highlight regions while don't have to parse the whole file?

**Comment by trishume** [comment]
There's no way in general to not lose highlighting correctness without parsing the file from the beginning at least once. Think of opening a quotation mark at the beginning of a long file being able to change the whole file's highlighting.

What you can do is cache `ParseState`s every once in a while and working back from there. See [the docs](https://docs.rs/syntect/3.1.0/syntect/parsing/struct.ParseState.html). By changing how frequently you cache parse states you can trade off between memory usage and syntax highlighting latency, knowing that syntect can highlight about 15k lines per second for a complex syntax.

Also see everything linked to in [Raph's blog post](https://raphlinus.github.io/personal/2017/10/12/what-im-working-on.html) where he talks about highlighting state caching using syntect.

**Comment by trishume** [comment]
The best document is [rope science 11](https://github.com/xi-editor/xi-editor/blob/master/docs/docs/rope_science_11.md), which has moved since that blog post linked to it.

**Comment by slmjkdbtl** [comment]
Thanks! I'll look into those
