### ISSUE TITLE
bug: `tokens_to_classed_spans` is private

### ISSUE THREAD

**Issue by PoiScript** [trishume/syntect#240]
The `tokens_to_classed_html` function is deprecated since 3.1.0 in favor of `tokens_to_classed_spans`. But `tokens_to_classed_spans` is actually [private](https://github.com/trishume/syntect/blob/6d6cf175a221544a1a2136bbe559d7fd117fe1ad/src/html.rs#L161).

**Comment by trishume** [comment]
Whoooops, will try and fix that and push a new release later today

**Comment by trishume** [comment]
I published `v3.2.0` with this fixed.
