### ISSUE TITLE
Example for returning HTML code of syntax-highlighted file using sublime-syntax file.

### ISSUE THREAD

**Issue by ChrisMGeo** [trishume/syntect#245]
Sorry if this is bothersome, but I'm pretty new to Rust so I don't know how to do what I am asking with the current knowledge I have.

What I am asking for is this, say I have a string that contains the file's text, a string corresponding to the location of a  sublime-syntax file and a string corresponding to the location of a tmtheme file, how would I return a syntax-highlighted HTML string.

**Comment by Memorion** [comment]
Here are the docs: https://docs.rs/syntect/3.2.0/syntect/html/index.html 
and here is a sample: https://github.com/trishume/syntect/blob/master/examples/synhtml.rs

**Comment by ChrisMGeo** [comment]
@Memorion Thanks for the answer and sorry for the late reply, but I believe that the function I am looking for is syntect::html::highlighted_html_for_string(https://docs.rs/syntect/3.2.0/syntect/html/fn.highlighted_html_for_string.html), however how do i declare a SyntaxSet and SyntaxReference (sorry if that's wrong) with a sublime-syntax file.

**Comment by trishume** [comment]
Look at the docs for `SyntaxSet` and `SyntaxSetBuilder`, there are a variety of ways to load files, folders and built in syntaxes. Then a bunch of methods to find a specific syntax.

**Comment by ChrisMGeo** [comment]
@trishume Thanks for the feedback. However I have one small doubt/feature-request  -  From what I understand the `SyntaxSet` is a group of syntaxes (I think it is `SyntaxReference`) from which a single syntax is used for highlighting. Wouldn't it be better if you could do the `syntect::highlighted_html_for_string` with a `SyntaxReference` only and without a `SyntaxSet`.
Please do correct me if I'm wrong anywhere.

**Comment by keith-hall** [comment]
my understanding is that, because many syntax definitions refer to other syntax definitions, the `SyntaxSet` is necessary. Otherwise PHP wouldn't have HTML and JS highlighted properly etc.

**Comment by trishume** [comment]
Yah Keith is correct, if you want to highlight with only one syntax you can make a set of only one syntax. Additionally the `SyntaxReference` is actually just a lightweight reference into the `SyntaxSet`.

**Comment by Enselic** [comment]
This seems sorted out. Let's close this issue now.
