### ISSUE TITLE
Panic crashes when parsing python code using legit Python.sublime-syntax files

### ISSUE THREAD

**Issue by brupelo** [trishume/syntect#248]
Consider this python file `test_crash.py`:

    ws = r"[-[\]!\"#$%&'()*+,./:;<=>?@\\^`{|}~]"

And then this simple snippet:

    from pathlib import Path
    from pysyntect import *

    crash_line = Path("test_crash.py").read_text().splitlines(True)[0]

    # Test1) It doesn't crash using builtin syntax
    ss = SyntaxSet.load_defaults_nonewlines()
    syntax = ss.find_syntax_by_extension("py")
    ParseState(syntax).parse_line(crash_line, ss)
    print("Test1 finished succesfully")

    # Test2) Pani crashes with both Python.sublime-syntax (from build 3149 & 3176)
    syntax = SyntaxDefinition.load_from_str(
        # Path("D:/sources/personal/python/pyblime/data/st_build_3149/syntax/Python.sublime-syntax").read_text(),
        Path("Python.sublime-syntax").read_text(),
        True
    )
    builder = SyntaxSetBuilder()
    builder.add(syntax)
    ss = builder.build()
    syntax = ss[0]
    ParseState(syntax).parse_line(crash_line, ss)
    print("Test2 finished succesfully")

When I run the script nothing bad will happen when using the python syntax file shipped with syntect, so far so good... But when I decide to use either the Python sublime-syntax file shipped with Sublime release 3149 or release 3176 I'll get panic crashes in both cases:

    Test1 finished succesfully
    thread '<unnamed>' panicked at 'Can only call resolve on linked references: ByScope { scope: <source.regexp.python>, sub_context: None }', D:\sources\others\sources_editors\syntect\src\parsing\syntax_definition.rs:193:18
    note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.

Which references to this one [https://github.com/trishume/syntect/blob/master/src/parsing/syntax_definition.rs#L193](https://github.com/trishume/syntect/blob/master/src/parsing/syntax_definition.rs#L193).

I've uploaded to dropbox both sublime-syntax files:

- [Python_3176.sublime-syntax](https://www.dropbox.com/s/hbjtlyrbljem6nv/Python_3176.sublime-syntax?dl=0)
- [Python_3149.sublime-syntax](https://www.dropbox.com/s/dmoea0q7ba549iz/Python_3149.sublime-syntax?dl=0)

**Comment by brupelo** [comment]
Ok, I've found the reason why I was getting these panic crashese, it seems I needed to add `Regular Expressions (Python).sublime-syntax` file to the `SyntaxSetBuilder` object.

That said, still one question remains to me... how can I capture these panic exceptions in order to reraise a python exception? Right now I've got this:

    pub fn parse_line(&mut self, line: &str, syntax_set: &SyntaxSet) -> Vec<(usize, ScopeStackOp)> {
        let mut res = Vec::new();
        for v in self.wrap.parse_line(line, &syntax_set.wrap) {
            res.push((v.0, ScopeStackOp { wrap: v.1 }));
        }
        return res;
    }

but if a panic exception raises my editor won't be able to handle the error :(... I've tried using [https://doc.rust-lang.org/std/panic/fn.catch_unwind.html](https://doc.rust-lang.org/std/panic/fn.catch_unwind.html) but a lot of compiler errors were spawned, ie:

    pub fn parse_line(&mut self, line: &str, syntax_set: &SyntaxSet) -> PyResult<Vec<(usize, ScopeStackOp)>> {
        let result = panic::catch_unwind(|| {
            self.wrap.parse_line(line, &syntax_set.wrap);
        });

        if result.is_err() {
            Err(exceptions::ValueError::py_err("ParseState.parse_line"))
        } else {
            let mut res = Vec::new();
            for v in self.wrap.parse_line(line, &syntax_set.wrap) {
                res.push((v.0, ScopeStackOp { wrap: v.1 }));
            }
            Ok(res)
        }
    }

<details>
<summary>
Errors
</summary>

       Compiling pysyntect v0.1.0 (D:\sources\personal\python\pysyntect)
    error[E0277]: the type `&mut &mut parser::ParseState` may not be safely transferred across an unwind boundary
      --> src\parser.rs:63:22
       |
    63 |         let result = panic::catch_unwind(|| {
       |                      ^^^^^^^^^^^^^^^^^^^ `&mut &mut parser::ParseState` may not be safely transferred across an unwind boundary
       |
       = help: within `[closure@src\parser.rs:63:42: 65:10 self:&mut &mut parser::ParseState, line:&&str, syntax_set:&&syntax_set::SyntaxSet]`, the trait `std::panic::UnwindSafe` is not implemented for `&mut &mut parser::ParseState`
       = note: required because it appears within the type `[closure@src\parser.rs:63:42: 65:10 self:&mut &mut parser::ParseState, line:&&str, syntax_set:&&syntax_set::SyntaxSet]`
       = note: required by `std::panic::catch_unwind`

    error[E0277]: the type `std::cell::UnsafeCell<std::option::Option<syntect::parsing::syntax_set::FirstLineCache>>` may contain interior mutability and a reference may not be safely transferrable across a catch_unwind boundary
      --> src\parser.rs:63:22
       |
    63 |         let result = panic::catch_unwind(|| {
       |                      ^^^^^^^^^^^^^^^^^^^ `std::cell::UnsafeCell<std::option::Option<syntect::parsing::syntax_set::FirstLineCache>>` may contain interior mutability and a reference may not be safely transferrable across a catch_unwind boundary
       |
       = help: within `&syntax_set::SyntaxSet`, the trait `std::panic::RefUnwindSafe` is not implemented for `std::cell::UnsafeCell<std::option::Option<syntect::parsing::syntax_set::FirstLineCache>>`
       = note: required because it appears within the type `lazycell::AtomicLazyCell<syntect::parsing::syntax_set::FirstLineCache>`
       = note: required because it appears within the type `syntect::parsing::syntax_set::SyntaxSet`
       = note: required because it appears within the type `syntax_set::SyntaxSet`
       = note: required because it appears within the type `&syntax_set::SyntaxSet`
       = note: required because of the requirements on the impl of `std::panic::UnwindSafe` for `&&syntax_set::SyntaxSet`
       = note: required because it appears within the type `[closure@src\parser.rs:63:42: 65:10 self:&mut &mut parser::ParseState, line:&&str, syntax_set:&&syntax_set::SyntaxSet]`
       = note: required by `std::panic::catch_unwind`

    error[E0277]: the type `std::cell::UnsafeCell<std::option::Option<onig::Regex>>` may contain interior mutability and a reference may not be safely transferrable across a catch_unwind boundary
      --> src\parser.rs:63:22
       |
    63 |         let result = panic::catch_unwind(|| {
       |                      ^^^^^^^^^^^^^^^^^^^ `std::cell::UnsafeCell<std::option::Option<onig::Regex>>` may contain interior mutability and a reference may not be safely transferrable across a catch_unwind boundary
       |
       = help: within `&syntax_set::SyntaxSet`, the trait `std::panic::RefUnwindSafe` is not implemented for `std::cell::UnsafeCell<std::option::Option<onig::Regex>>`
       = note: required because it appears within the type `lazycell::AtomicLazyCell<onig::Regex>`
       = note: required because it appears within the type `syntect::parsing::syntax_definition::MatchPattern`
       = note: required because it appears within the type `syntect::parsing::syntax_definition::Pattern`
       = note: required because it appears within the type `*const syntect::parsing::syntax_definition::Pattern`
       = note: required because it appears within the type `std::ptr::Unique<syntect::parsing::syntax_definition::Pattern>`
       = note: required because it appears within the type `alloc::raw_vec::RawVec<syntect::parsing::syntax_definition::Pattern>`
       = note: required because it appears within the type `std::vec::Vec<syntect::parsing::syntax_definition::Pattern>`
       = note: required because it appears within the type `syntect::parsing::syntax_definition::Context`
       = note: required because it appears within the type `*const syntect::parsing::syntax_definition::Context`
       = note: required because it appears within the type `std::ptr::Unique<syntect::parsing::syntax_definition::Context>`
       = note: required because it appears within the type `alloc::raw_vec::RawVec<syntect::parsing::syntax_definition::Context>`
       = note: required because it appears within the type `std::vec::Vec<syntect::parsing::syntax_definition::Context>`
       = note: required because it appears within the type `syntect::parsing::syntax_set::SyntaxSet`
       = note: required because it appears within the type `syntax_set::SyntaxSet`
       = note: required because it appears within the type `&syntax_set::SyntaxSet`
       = note: required because of the requirements on the impl of `std::panic::UnwindSafe` for `&&syntax_set::SyntaxSet`
       = note: required because it appears within the type `[closure@src\parser.rs:63:42: 65:10 self:&mut &mut parser::ParseState, line:&&str, syntax_set:&&syntax_set::SyntaxSet]`
       = note: required by `std::panic::catch_unwind`

    error: aborting due to 3 previous errors
</details>

Any suggestion?

**Comment by trishume** [comment]
Yah, syntect isn't very good at error handling in a use case where you might be loading user-supplied syntaxes. If you know the syntaxes are good then you don't need to handle panics since they just won't happen.

I'm not sure how catching panics works, I've never used it, but I suspect it might be difficult to expose to Python. I'm guessing the problem _might_ be that you can't use any structure that you gave access to in a `catch_unwind` block after that block because it might have its internal invariants messed up by the panic. Which is a problem in Python bindings because if you catch the exception you can then turn around and still call methods on the object. Maybe there's a way to solve this but it might be tricky and I can't help you with it.

The ideal solution is for syntect not to panic on invalid syntaxes, but that would take a decent amount of effort I'm not interested in putting in, although I'd accept contributions. Either by giving proper Rust `Result` errors or by just failing gracefully by say ignoring uses of invalid references.

**Comment by brupelo** [comment]
I see, alright, clear... if you (who are the rust guru here) are saying it'll be tricky I'll just forget about it, otherwise I'm sure I'd end up wasting few hours trying to find a workaround to make it compile, which is not worth it. 

From now on I'll just make sure the syntaxes I use on the editor won't simply produce these panic errors and if that ever happens I'll consider it a limitation and I'll just try to fix/modify the user-supplied sublime-syntax.

Closing this ticket now as it seems everything has become pretty much clear now.
