### ISSUE TITLE
does syntect support vscode tmlanguage files?

### ISSUE THREAD

**Issue by nurpax** [trishume/syntect#249]
Vscode seems to natively use tmlanguage files that have been converted to json.

I tried converting some tmlanguage specs to json and loaded into syntect.  But these tmlanguage specs seem to be missing the "contexts" element that's present in sublime-text language grammars.

I couldn't quite tell from syntect docs which of these different flavors of language grammars are supported?

Example grammar: https://github.com/microsoft/TypeScript-TmLanguage/blob/master/TypeScriptReact.YAML-tmLanguage

**Comment by trishume** [comment]
syntect only supports the `.sublime-syntax` format described [here](https://www.sublimetext.com/docs/3/syntax.html). Your only hope for using JSON tmLanguage files is to first convert them to standard XML tmLanguage files, then use a converter from `tmLanguage` to `sublime-syntax` like the one included in Sublime Text or in a few different Github repos. Or convert it yourself manually by learning the formats.

**Comment by trishume** [comment]
You can also look around for a version that's already in `.sublime-syntax` format. There's a lot of them here, including one for TypeScriptReact: https://github.com/sharkdp/bat/tree/master/assets/syntaxes

**Comment by nurpax** [comment]
Thanks @trishume!  This is for a syntax spec I wrote myself for VSCode (https://github.com/nurpax/c64jasm/blob/master/vscode/syntaxes/c64jasm.tmLanguage.json), so there's no ST version of it.  I mainly need it for syntax highlighting code samples to docs, so maybe I'll just whip something together with regex.
