### ISSUE TITLE
Infinite Loop on C files

### ISSUE THREAD

**Issue by trishume** [trishume/syntect#25]
There's an infinite loop bug on some C files due to a broken pattern in the default Sublime C syntax that can cause an infinite loop. Despite the pattern being borked syntect should handle this gracefully like Sublime Text obviously does.

## Example 

text: `struct{estruct`

First it matches
```yaml
- match: '(?={{before_tag}})'
   push: data-structures
```
at position 8 and then matches
```yaml
- match: '(?=\S)'
      pop: true
```
at the same position, and then repeats.

## Possible solution

No single pattern should be able to trigger more than once at the same location. Maybe keep track of which patterns have triggered and ignore any further matches, resetting the store upon advancing. The trick is maintaining performance.

**Comment by robinst** [comment]
Is this released yet?

**Comment by trishume** [comment]
Whoops yah I forgot to release, thanks for reminding me.
