### ISSUE TITLE
Serialized Output (other than XML)

### ISSUE THREAD

**Issue by turbo** [trishume/syntect#257]
First of all, nice work! I'm currently evaluating syntect for internal use and I'll basically have to hook it up to existing tooling. My use case isn't highlighting, but code analysis. Therefore, a straight serialized output would be perfect (JSON or whatever), so I can process the tokens in other programs.

So far, I've found `ClassedHTMLGenerator` which technically produces XML (as HTML with classes), but I feel like that's a workaround rather than a solution.

It's also hard to map the XML output back to the original file, because it contains no positional information. What I need is something like a JSONL output for each input line, where each entry would look something like this:

```json
[{"column": 42, "token": "foobar", "type": "entity.keyword"}]
```

**Comment by turbo** [comment]
I've also found this parser: 

Which for this file:

```html
<!DOCTYPE html>
<html>
<head>
    <title></title>

    <script type="text/javascript">
        const text = "Hello World!";
        console.log(text);
    </script>
</head>
<body>

</body>
</html>
```

Outputs something like this (ignoring non-token-starting columns):

```text
1:1 text.html.basic meta.tag.sgml.html punctuation.definition.tag.html 
1:3 text.html.basic meta.tag.sgml.html meta.tag.sgml.doctype.html entity.name.tag.doctype.html 
1:10 text.html.basic meta.tag.sgml.html meta.tag.sgml.doctype.html 
1:11 text.html.basic meta.tag.sgml.html meta.tag.sgml.doctype.html 
1:15 text.html.basic meta.tag.sgml.html punctuation.definition.tag.html 
1:16 text.html.basic 
2:1 text.html.basic meta.tag.structure.any.html punctuation.definition.tag.begin.html 
2:2 text.html.basic meta.tag.structure.any.html entity.name.tag.structure.any.html 
2:6 text.html.basic meta.tag.structure.any.html punctuation.definition.tag.end.html 
2:7 text.html.basic 
3:1 text.html.basic meta.tag.structure.any.html punctuation.definition.tag.begin.html 
3:2 text.html.basic meta.tag.structure.any.html entity.name.tag.structure.any.html 
3:6 text.html.basic meta.tag.structure.any.html punctuation.definition.tag.end.html 
3:7 text.html.basic 
4:1 text.html.basic 
4:5 text.html.basic meta.tag.inline.any.html 
<snip>
```

using this core loop:

```js
    const result = Array.from(flatMap(
            parse(unpacked, text, syntaxProvider),
            function* ([[begin, end], scope]) {
                const row = begin[1];
                for (let col = begin[2]; col < end[2]; col++) {
                    if (!(col === begin[2]))
                    continue;
                    yield `${row+1}:${col+1} ${scope}`;
                }
            }
        ));
```

I wonder how I can achieve something similar with syntect. Using the classed HTML parser, I get tons of repetition in the output. Some source lines are presents three or more times, parsed differently. But this is probably down to bugs in my code.

**Comment by turbo** [comment]
For now I've hacked together something that outputs JSONL like this:

```jsonl
{"index":0,"length":1,"line":0,"scope":["source.yaml","comment.line.number-sign.yaml","punctuation.definition.comment.line.number-sign.yaml"],"source":"#"}{"index":1,"length":56,"line":0,"scope":["source.yaml","comment.line.number-sign.yaml"],"source":" Make codecov not add verbose comments to pull requests\n"}
{"index":0,"length":7,"line":1,"scope":["string.unquoted.plain.out.yaml","entity.name.tag.yaml"],"source":"comment"}{"index":7,"length":1,"line":1,"scope":["punctuation.separator.key-value.mapping.yaml"],"source":":"}{"index":8,"length":1,"line":1,"scope":[],"source":" "}{"index":9,"length":5,"line":1,"scope":["constant.language.boolean.yaml"],"source":"false"}
```

using serde and a heavily modified version of `ClassedHTMLGenerator`. So consider this issue / request low-priority.

**Comment by trishume** [comment]
For performance reasons (and because Rust is cool) I suggest you consider doing whatever code analysis you want to do in Rust, and then just shipping the results of the analysis out over JSON.

Take a look at the `synstats.rs` example for something that does some code analysis.

**Comment by turbo** [comment]
I appreciate the sentiment, but the analysis part is many tens of thousand of lines of third party code plus some proprietary services, can't rewrite those :wink:
