### ISSUE TITLE
Update included dump of Sublime text syntax definitions?

### ISSUE THREAD

**Issue by robinst** [trishume/syntect#26]
Hey. It looks like there needs to be a release for #25.

Would it be too much to ask to update to the newest syntax definitions from Sublime text :)? Looks like there have been some updates for Rust, among others: https://github.com/sublimehq/Packages/commits/master/Rust

**Comment by trishume** [comment]
Unfortunately, since I last updated the packages they added a new feature, so if I update indiscriminately now it will break the definition for at least Ruby and possibly some others. 

See https://github.com/sublimehq/Packages/pull/466

I might look into implementing this today or tomorrow.

**Comment by trishume** [comment]
I'm working on this in https://github.com/trishume/syntect/issues/26

**Comment by robinst** [comment]
(^ should be #27 I think)
