### ISSUE TITLE
Build failed for onig

### ISSUE THREAD

**Issue by elgunhuseynli** [trishume/syntect#264]
Examples aren't compiling on Windows 10.

```
Compiling onig_sys v69.2.0
error: failed to run custom build command for `onig_sys v69.2.0`
...
--- stdout
cargo:warning=couldn't execute `llvm-config --prefix` (error: The system cannot find the file specified. (os error 2))
cargo:warning=set the LLVM_CONFIG_PATH environment variable to a valid `llvm-config` executable
```

**Comment by elgunhuseynli** [comment]
Oniguruma is regex library written in C. Why not just use Rust's own regex library? So we don't get build errors like that.

**Comment by keith-hall** [comment]
https://github.com/rust-onig/rust-onig/issues/109

> Why not just use Rust's own regex library?

see https://github.com/trishume/syntect/issues/12

**Comment by trishume** [comment]
See the new pure-Rust `fancy-regex` mode introduced in [v4.0.0](https://github.com/trishume/syntect/pull/270) to avoid this issue!

Still hoping that onig's build will eventually improve but for now `fancy-regex` is a good option.

**Comment by Enselic** [comment]
Duplicate of #12

**Comment by Enselic** [comment]
This issue can be closed with motivation:

Effectively a duplicate of #12
