### ISSUE TITLE
Is it possible to merge two SyntaxSets?

### ISSUE THREAD

**Issue by luser** [trishume/syntect#278]
I was trying to add a few additional syntaxes to a utility I was writing. I had previously been using `SyntaxSet::load_defaults_newlines()`. I took a few `.sublime-syntax` files and wrote a helper program that used `SyntaxSet::add_from_folder` to load them and `dumps::dump_to_file` to dump them to a binary file. I changed my main program to use `dumps::from_binary(include_bytes!(...)` to get a `SyntaxSet`, but then I can't find any way to merge the contents of the two sets. I saw that I could use `SyntaxSet::into_builder()` to get a `SyntaxSetBuilder` and that has an `add` method but it takes a `SyntaxDefinition` which I can't get out of `SyntaxSet`. It looks like `SyntaxSetBuilder` has those internally but doesn't expose any public API to get them out?

From looking at the source it looks like I could effectively reimplement `load_syntax_file` to load my syntax files into a `Vec<SyntaxDefinition>` and round-trip that the same way I had been with a `SyntaxSet`. Then I could use `SyntaxSetBuilder::add` to add each entry to the default set. That feels kind of convoluted. Is there something I'm missing or is this use case just not well supported currently?

Just so this doesn't sound too negative I want to say that I love syntect and it's amazingly useful!

**Comment by sharkdp** [comment]
Not sure if this is really want you want, but we do merge syntax sets in `bat` here: https://github.com/sharkdp/bat/blob/90ee93967115d97491f56ce198e9556008bc29f5/src/assets.rs#L51-L67

But I guess it only works if the second set is loaded/added from a folder.

**Comment by trishume** [comment]
Yah I think what @sharkdp suggests works fine. Another option is to download or add as a submodule the same commit of the Sublime HQ packages repo that the built in syntect syntax sets are made from, and then use Cargo features to turn off the inclusion of the default sets to save binary size.

**Comment by Enselic** [comment]
I also think that what `bat` is doing should work for your use case?

Closing for now. Feel free to reopen if you still have troubles.
