### ISSUE TITLE
Rust syntax highlighting not correct in "use" section

### ISSUE THREAD

**Issue by ojensen5115** [trishume/syntect#28]
I don't have Sublime Text so can't verify whether the issue is present there as well. When  highlighting a Rust file, it seems choose arbitrary lines to highlight in the "use" section:

This text:

    #[macro_use] extern crate iron;
    extern crate router;
    extern crate params;
    extern crate bodyparser;

    extern crate crypto;
    extern crate rand;
    extern crate syntect;

    use std::fs;
    use std::fs::File;
    use std::path::Path;
    use std::io::Write;
    use std::io::Read;
    use std::io::BufRead;

    use iron::headers::ContentType;
    use iron::modifiers::Header;
    use iron::prelude::*;
    use iron::status;

    use params::{Params, Value};
    use router::Router;

    use crypto::hmac::Hmac;
    use crypto::mac::Mac;
    use crypto::sha2::Sha256;

    use rand::Rng;

    use syntect::parsing::SyntaxSet;
    use syntect::highlighting::{ThemeSet, Style};
    use syntect::util::as_24_bit_terminal_escaped;
    use syntect::easy::HighlightLines;

highlights with the Rust highlighter (as determined by the "rs" extension) are as follows:

![screenshot](http://i.imgur.com/s0M4uUH.png)

Note that the keyword "use" is sometimes colored, sometimes not.

**Comment by trishume** [comment]
In the process of fixing #25 I added a check that was a bit overzealous and stopped Rust from working correctly. I made my infinite loop detection more conservative and now Rust works and it should still detect infinite loops.

Thanks for the report!
