### ISSUE TITLE
Use in threaded context seems to require unsafe wrapper struct

### ISSUE THREAD

**Issue by ojensen5115** [trishume/syntect#29]
Documentation states that the SyntaxSet and ThemeSet should be loaded once at program startup (and indeed reloading them whenever highlighting is needed hurts performance). However, SyntaxSet does not appear to be threadsafe, possibly due to the internal use of RefCell in SyntaxDefinition.

As a result, the simplest way of getting it to work in Iron that I have found requires the following (unsafe) dance:

```
struct HighlighterSyntaxSet {
    ss: SyntaxSet,
}
unsafe impl Sync for HighlighterSyntaxSet {}

lazy_static! {
    static ref HL_SYNTAX_SET: HighlighterSyntaxSet = {
        let ss = SyntaxSet::load_defaults_newlines();
        HighlighterSyntaxSet {ss: ss}
    };
}
```

Using it directly without the unsafe wrapper results in the following error:

```
the trait `std::marker::Sync` is not implemented for `std::rc::Rc<std::cell::RefCell<syntect::parsing::syntax_definition::Context>>`
    = note: `std::rc::Rc<std::cell::RefCell<syntect::parsing::syntax_definition::Context>>` cannot be shared between threads safely
    = note: required because it appears within the type `std::option::Option<std::rc::Rc<std::cell::RefCell<syntect::parsing::syntax_definition::Context>>>`
    = note: required because it appears within the type `syntect::parsing::SyntaxDefinition`
    = note: required because of the requirements on the impl of `std::marker::Sync` for `std::ptr::Unique<syntect::parsing::SyntaxDefinition>`
    = note: required because it appears within the type `alloc::raw_vec::RawVec<syntect::parsing::SyntaxDefinition>`
    = note: required because it appears within the type `std::vec::Vec<syntect::parsing::SyntaxDefinition>`
    = note: required because it appears within the type `syntect::parsing::SyntaxSet`

```

The use of lazy_static here is simply to avoid the more complex code necessary for using the `persistent` crate, or `Arc`s directly. I don't believe it affects the issue at hand.

All that said, it is of course entirely possible I'm using this incorrectly -- I'm somewhat new to Rust.

**Comment by trishume** [comment]
So that unsafe wrapper can actually do bad things because the lazy loading of regexes modifies the structure, and you don't want that to happen in two threads at the same time.

See https://github.com/trishume/syntect/issues/20 for a long overview of the issues and some ways around the issue.

**Comment by ojensen5115** [comment]
Thanks, I appreciate the help and the link.

**Comment by trishume** [comment]
I'm closing this because of #82.
