### ISSUE TITLE
add a syntect::easy::HighlightLines::reset function

### ISSUE THREAD

**Issue by SamHSmith** [trishume/syntect#306]
add a syntect::easy::HighlightLines::reset(&mut self) so that I don't have to recreate the HighlightLines on every highlight. Allow me to reset the internal state directly for both practicality and perf.

**Comment by trishume** [comment]
I'm unlikely to implement this myself although I would accept a PR. The perf impact of just re-assigning a mutable stack variable to `HighlightLines::new` every time should be pretty negligible compared to the cost of highlighting. It allocates a handful of vectors and avoiding that would be nice, but also every line allocates at least one vector every line. Profiler data would change my mind though.

**Comment by SamHSmith** [comment]
Started working on a PR and I understand what you mean now. It's probably easier to let rust's jemalloc make the allocations quick and cache friendly.
