### ISSUE TITLE
Separate feature for theme/syntax bundling

### ISSUE THREAD

**Issue by sidju** [trishume/syntect#310]
If someone writes a 16-color application, or for some other reason don't want to have bundled themes, it would be good for them to be able to remove the bundled themes without losing the bundled syntax definitions.

I might have missed something, but I don't think you currently can disable the embedding of themes.

**Comment by Enselic** [comment]
Correct, both themes and syntaxes are behind the same feature: "assets"

**Comment by Enselic** [comment]
I think this is worth considering before we bump major version. I'll take a look at this.

**Comment by Enselic** [comment]
@sidju Would you mind checking if #417 solves this problem for you? Big thanks in advance!

**Comment by sidju** [comment]
I have since moved over to parsing and building my own syntax definitions, and thus don't need this change anymore. That said I still think it is useful, the branch diff looks good and it worked well for me to build, although I haven't tested the specific split.
