### ISSUE TITLE
meta.block scopes is split in two.

### ISSUE THREAD

**Issue by kobrir** [trishume/syntect#311]
I am trying to get a list of scopes for a given position in the string, so that I can select the current scope in the editor, but there is a problem with the block scopes. 
For example for this rust line:
`{"sfg"}`

I get this scope list from ParseState::parse_line:

```
(0, Push(<source.rust>)), 
 (0, Push(<meta.block.rust>)), 
  (0, Push(<punctuation.section.block.begin.rust>)), 
  (1, Pop(1)), 
  (1, Push(<string.quoted.double.rust>)), 
   (1, Push(<punctuation.definition.string.begin.rust>)), 
   (2, Pop(1)), 
   (5, Push(<punctuation.definition.string.end.rust>)), 
   (6, Pop(1)), 
  (6, Pop(1)), 
 (6, Pop(1)), 
 (6, Push(<meta.block.rust>)), 
  (6, Push(<punctuation.section.block.end.rust>)), 
(7, Pop(2))

```
You can see that there is only one string.quoted.double.rust scope, but meta.block.rust is split in two, the first parts is from 0 to 6, and the second from 6 to 7.
It makes it hard to select the current block. For strings I can just select everything from the start of the corresponding scope to the end, but for a block I will miss the last character if I did the same.

Is this splitting intentional? Maybe there is some workaround?

**Comment by keith-hall** [comment]
This is likely due to how the syntax definition is structured, and/or the push/set/pop rules which would waste performance to special case it not to execute pop operations for scopes which will immediately be pushed back onto the stack. As you are not interested in individual tokens, it should just be possible to extend your matched span until you the first non-empty operation where the scope you want is no longer on the stack, no?

**Comment by kobrir** [comment]
If I extend the scope then, for example, two adjacent blocks would be selected as one, but I want to select only the current one.

**Comment by keith-hall** [comment]
As [we can see from looking at the syntax definition, the `meta_scope` doesn't apply `meta.block` to the closing `}`, it is scoped as part of the token](https://github.com/sublimehq/Packages/blob/8434c7d8a9211698e73944846ab9c03ca21d1a55/Rust/Rust.sublime-syntax#L314-L320). So nothing can be done about this in `syntect`, it is behaving correctly.

So I guess you can either change the syntax definition, or use the canonical method of checking where the `punctuation.section.block.begin.rust` and `punctuation.section.block.end.rust` tokens are to determine where a block ends and another begins.

**Comment by Enselic** [comment]
Thanks for solid debugging as usual, Keith.

Closing this then.
