### ISSUE TITLE
gutter colors are not set in most of the bundled themes.

### ISSUE THREAD

**Issue by ivanceras** [trishume/syntect#315]
I tried to use the gutter colors from themeset but it's not set, is this intended?
I've tried the `Solarized` and the `base16-` variants.

**Comment by keith-hall** [comment]
It's not intended by us, I would say - they are just third party color schemes after all. I guess that the color schemes were created for TextMate / Sublime Text and those applications would assign some default color if it was unset - maybe syntect could do the same, but I'm not sure how it is computed in Sublime Text - ideally we would emulate the same behavior and come up with the same colors...

**Comment by ivanceras** [comment]
Is there a link to the source of this packages? Maybe the one bundled with syntect is outdated.

**Comment by keith-hall** [comment]
They are just submodules, so GitHub links them:
https://github.com/trishume/syntect/tree/master/testdata

**Comment by ivanceras** [comment]
The linked repo is using a very [old version](https://github.com/braver/Solarized/tree/bcd6234b4f5f96d3fd27db079268b5757053072a). It looks like I need to load an updated themeset using [discover_theme_paths](https://docs.rs/syntect/4.4.0/syntect/highlighting/struct.ThemeSet.html#method.discover_theme_paths) rather than using the `load_defaults`
