### ISSUE TITLE
Help with implementing with WASM?

### ISSUE THREAD

**Issue by ChrisMGeo** [trishume/syntect#324]
Hello, I'm pretty new to this library and WASM, and rust in general. I'm trying to use a custom "class"(albeit a terrible one) in order to highlight text, using this library. My "library" is located [here](https://github.com/ChrisMGeo/syntect-wasm-trial). This library works normally using a `main.rs`, but for some reason using wasm doesn't work. Making the wasm and importing and using it in `index.js` is of no problem. But on running `Highlighter.new("path/to/theme")` from my library causes an error.
```
bootstrap.js:5 Error importing `index.js`: RuntimeError: unreachable
    at http://localhost:8080/d1ab8293da4817fae31b.module.wasm:wasm-function[565]:0x75c17
    at http://localhost:8080/d1ab8293da4817fae31b.module.wasm:wasm-function[784]:0x7ef7d
    at http://localhost:8080/d1ab8293da4817fae31b.module.wasm:wasm-function[1335]:0x8a93f
    at http://localhost:8080/d1ab8293da4817fae31b.module.wasm:wasm-function[1251]:0x899c9
    at http://localhost:8080/d1ab8293da4817fae31b.module.wasm:wasm-function[1337]:0x8a9a3
    at http://localhost:8080/d1ab8293da4817fae31b.module.wasm:wasm-function[857]:0x8111c
    at http://localhost:8080/d1ab8293da4817fae31b.module.wasm:wasm-function[1133]:0x8798d
    at highlighter_new (http://localhost:8080/d1ab8293da4817fae31b.module.wasm:wasm-function[858]:0x81167)
    at Function.new (webpack:///../pkg/syntect_web_bg.js?:120:87)
    at eval (webpack:///./index.js?:4:78)
eval @ bootstrap.js:5

```

**Comment by keith-hall** [comment]
Did you find a solution? :) sorry for the lack of replies - I am also not so experienced with rust or wasm. I know there are some simple syntect wasm examples around, though, so maybe they will help. You should be able to find one linked in an issue on this repo iirc. Let me know if you need me to find it :)
