### ISSUE TITLE
Export `Escape` formatter

### ISSUE THREAD

**Issue by camdencheek** [trishume/syntect#329]
I'd like to use the the [Escape](https://sourcegraph.com/github.com/trishume/syntect/-/blob/src/escape.rs?subtree=true#L18:45) wrapper for emitting HTML in a custom format, but it's not exported for use outside the crate. Would it be possible to export this? It's nice for convenience.

**Comment by Enselic** [comment]
Closing this now since https://github.com/trishume/syntect/pull/330 was closed
