### ISSUE TITLE
Proposal: single location for syntax files for any project using syntect

### ISSUE THREAD

**Issue by mnemnion** [trishume/syntect#333]
Syntect is a great piece of software, and I have (at least) three applications using it on my computer: [bat](https://github.com/sharkdp/bat), [amp](https://github.com/jmacdonald/amp), and [delta](https://github.com/dandavison/delta). 

I expect there will be more in time! It's a wonderful building block. 

I use a couple custom `.sublime-syntax` files on a regular basis, and I opened up an [issue](https://github.com/jmacdonald/amp/issues/214) in amp to allow it to read the syntax files I already have in bat's config folder. They pointed out that I could use a symlink, and I probably will once they package a new release to get around a blocking bug. 

But it occurred to me that the real leverage would be for syntect itself to have a default config folder where syntax and theme directories live.  Programs such as bat could keep their `syntaxes` folder, but make it a symlink to e.g. `~/.config/syntect/syntaxes`, as could any other application using syntect.

**Comment by keith-hall** [comment]
Potentially related: https://github.com/trishume/syntect/issues/168

There's also some good points about how having a shared set of assets can complicate things here: https://github.com/sharkdp/bat/issues/919#issuecomment-616065576

**Comment by Enselic** [comment]
Yes, let's discuss and coordinate this in #168
