### ISSUE TITLE
Build is broken

### ISSUE THREAD

**Issue by raphlinus** [trishume/syntect#35]
The build is broken because of https://github.com/ebarnard/rust-plist/issues/16 , fix in review.

We'll want to update the version for plist as soon as that fix lands.

**Comment by trishume** [comment]
@raphlinus interesting thanks. I subscribed to all the relevant issues and will updated syntect when things get fixed.

**Comment by trishume** [comment]
Should be fixed by https://github.com/trishume/syntect/commit/798a3b9e3e17ce65589f8ff43cf5876ca99f1200

I'll push an update to crates.io once CI runs.

**Comment by trishume** [comment]
Done, I pushed version `1.1.1` with the fix. I also updated a bunch of things to new versions and relaxed the version constraints on a bunch of things so `syntect` doesn't cause as much dependency hell when you try and use other crates.
