### ISSUE TITLE
Proposal: Add Expect to list of languages supported

### ISSUE THREAD

**Issue by ShadowAce** [trishume/syntect#373]
I do a lot of expect scripting and I would use this tool to examine my expect scripts.  Using vim in order to get a pager is kinda sketchy.

**Comment by keith-hall** [comment]
Hi, thanks for your interest in syntect. We have no plans to bundle more syntax definitions/languages at this time (see https://github.com/trishume/syntect/issues/335#issuecomment-855028187). Note that syntect is designed to be a library for use by other tools, maybe you'd be interested in https://github.com/sharkdp/bat? If "Expect" is "expect.js" and can just be highlighted as JavaScript, then `bat` can easily be customized to do that.
