### ISSUE TITLE
Only annotate with class name

### ISSUE THREAD

**Issue by Keats** [trishume/syntect#38]
Would it be possible to have a mode where it only sets some classes like [Pygment](http://pygments.org) does? 
That makes it trivial for a end user (for example someone using a static site engine) to use whatever theme they want just by changing some CSS.

Looking at http://docs.sublimetext.info/en/latest/reference/color_schemes.html I couldn't find any info whether it's possible possible to have a custom theme that will just add a class rather than add a style?

Not a big deal if it's out of scope for the project

**Comment by trishume** [comment]
You can already kind of do this by using [html::tokens_to_classed_html()](http://thume.ca/rustdoc/syntect/syntect/html/fn.tokens_to_classed_html.html). You just have to write your own CSS selectors to highlight the scopes you want. Look at the [Sublime Text scope naming docs](https://www.sublimetext.com/docs/3/scope_naming.html) for the different categories that you might want to write selectors for.

Anything where syntect chooses whittles things down to a small number of classes for you like Pygment does is out of scope. If you want you can implement it yourself using syntect's API and modifying the code for `tokens_to_classed_html`.

**Comment by Keats** [comment]
I see, thanks!
