### ISSUE TITLE
RUSTSEC-2020-0159

### ISSUE THREAD

**Issue by dandavison** [trishume/syntect#385]
IIUC, projects using syntect are currently affected by [RUSTSEC-2020-0159](https://rustsec.org/advisories/RUSTSEC-2020-0159). This is because syntect depends on the plist crate, and plist depends on chrono, and chrono contains the security problem. There is an unreleased fix for this in plist: https://github.com/ebarnard/rust-plist/pull/72 so IIUC if that were released, and syntect were to update to it, then that would fix the issue. There is also current discussion in the chrono repo about fixing the situation there: https://github.com/chronotope/chrono/issues/499. cc @sharkdp 

(Or is there a feature-based workaround for now?)

**Comment by Enselic** [comment]
It would be great if someone could come up with a way to reproduce this with syntect.

**Comment by extrawurst** [comment]
I think its not only relevant if there is a reproducible way to trigger the actual bug using syntect. 
Most corporate policy prevents keeping RUSTSECs around.
In case of `syntect` its an easy fix once `plist` releases a version including the [fix](https://github.com/ebarnard/rust-plist/pull/72)

**Comment by Enselic** [comment]
Well, if there is no way to trigger the bug with syntect, there is no point to keep this issue open in syntect.

And if there *is* a way to trigger it, it is very useful to use that to confirm that the issue is gone once we bump plist.

**Comment by michaelblyons** [comment]
Looks like PList released a fix two days ago...?

**Comment by Enselic** [comment]
The thing is, syntect does not specify a version of plist. Only a minimal version. It is then up to clients of syntect to pick an actual version of plist. So I'm not sure what syntect should do here. Bump minimum version of list to 1.3.0? Then I think someone needs to show that syntect is actually affected by this bug.

Related: https://github.com/trishume/syntect/pull/397

**Comment by Enselic** [comment]
Since we are about to do a major bump I think we can we increase the minimum plist version without any concerns. I'll take care of that when I get time.

**Comment by Enselic** [comment]
As far as I can tell, https://github.com/trishume/syntect/pull/414 removes the indirect `chrono` dependency from `syntect`, which should be enough to fix this issue.

Any help with double-checking that would be appreciated. Otherwise we'll just have to assume the above PR solves this RUSTSEC issue for `syntect`.

**Comment by dandavison** [comment]
Hi @Enselic, thanks very much for working on this. I'm currently a bit confused about exactly what states of my dependency tree trigger the security audit failure but I can confirm that I can create a branch using #414 that passes security audit.

**Comment by Enselic** [comment]
Great! Thanks for checking!
