### ISSUE TITLE
Loading Theme from included string

### ISSUE THREAD

**Issue by tobiasvl** [trishume/syntect#392]
I'm not sure if I'm doing this right, as there doesn't seem to be much documentation on it, but I'm having trouble loading a Theme from an included string.

This works perfectly:
```rust
use syntect::highlighting::ThemeSet;
let theme = ThemeSet::get_theme(Path::new("Monokai.tmTheme")).unwrap();
```
However, I want to hardcode the theme instead of shipping it with the binary, but when I try this:
```rust
use syntect::highlighting::Theme;
use serde_xml_rs::from_str;
let theme: Theme = from_str(include_str!("Monokai.tmTheme")).unwrap();
```
I get the following error:
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Custom { field: "missing field `settings`" }'
```

The serde integration doesn't seem to be documented very heavily, so I just had to guess that I had to use `serde_xml_rs`. Maybe that's wrong, but I'm not sure, I'm not too experienced with serde. How can I achieve this?

**Comment by Enselic** [comment]
I think the following works. It doesn't cause a panic at least:

```rust
let mut theme_cursor = std::io::Cursor::new(include_bytes!("../Monokai.tmTheme"));
let theme = ThemeSet::load_from_reader(&mut theme_cursor).unwrap();
```

**Comment by tobiasvl** [comment]
@Enselic Yep, perfect! Thank you so much!
