### ISSUE TITLE
`discover_theme_paths` doesn't follow symbolic links

### ISSUE THREAD

**Issue by emeinhardt** [trishume/syntect#396]
Themes, like other components of a configuration, are often symlinked from some other location (e.g. a version controlled directory or as a result of something like [`nix` `home-manager`'s wrapper](https://github.com/nix-community/home-manager/issues/2482) around [`bat`](https://github.com/sharkdp/bat)).

[`discover_theme_paths` uses `WalkDir`](https://github.com/trishume/syntect/blob/ec62d80e33eeaf6ea3868fab452824789b672b49/src/highlighting/theme_set.rs#L25-L34), but doesn't use [the available option to follow symbolic links](https://github.com/BurntSushi/walkdir#example-follow-symbolic-links).

Could `syntect` be fixed/enhanced to follow symbolic links in `discover_theme_paths`?

**Comment by Enselic** [comment]
Sounds reasonable to me. While technically a breaking change (someone could in theory rely on the current behavior of symbolic links not being followed),  I don't think it would be a problem in practice to change the default behavior to follow symbolic links. I.e. I vote for keeping the current API and just change behavior. So let's treat it like a bug.

**Comment by Enselic** [comment]
Would be good to get this simple fix in 5.0.0 now that we need to do a major bump anyway. I'll take care of that when I get some time.

**Comment by Enselic** [comment]
@emeinhardt Would you mind verifying that #415 fixes this issue for you? Big thanks in advance!
