### ISSUE TITLE
panic on a svelte file

### ISSUE THREAD

**Issue by Canop** [trishume/syntect#421]
Here's the file:
```svelte
<script>
	import Navigation from '$lib/pages/Navigation.svelte';

	import '../app.postcss';
</script>

<Navigation />

<slot />

<style global lang="postcss">
	body,
	#svelte {
		@apply w-full h-full;
		@apply bg-neutral-100;
	}
</style>
```
It breaks both bat and broot, both using syntect 4.6.0.

![image](https://user-images.githubusercontent.com/617006/150413461-6d486858-3552-433d-8053-1c85fa8725e7.png)

```
thread 'main' panicked at 'Can only call resolve on linked references: ByScope { scope: <source.postcss>, sub_context: None }', /home/dys/.cargo/registry/src/github.com-1ecc6299db9ec823/syntect-4.6.0/src/parsing/syntax_definition.rs:191:18
stack backtrace:
   0: rust_begin_unwind
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/panicking.rs:517:5
   1: std::panicking::begin_panic_fmt
             at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/panicking.rs:460:5
   2: syntect::parsing::parser::ParseState::push_meta_ops
   3: <bat::printer::InteractivePrinter as bat::printer::Printer>::print_line
   4: bat::controller::Controller::print_file
   5: bat::controller::Controller::run_with_error_handler
   6: bat::run_controller
   7: bat::run
   8: bat::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by Enselic** [comment]
Thank you for the bug report.

This is most likely a variant of https://github.com/sharkdp/bat/issues/915

The plan is to fix this whole category of problems by falling back to Plain Text when referenced syntaxes are missing. This is what Sublime Text seems to be doing. There is some prototype code for that linked to from that issue. I hope to get around converting that prototype code to production code at some point, but there are currently more high prio things to do before that.

I don't think there is a ticket in syntect for this work, so we can keep this ticket open for that.

**Comment by Canop** [comment]
The problem IMO isn't about the fallback plan: that's the concern of the application instead. What's crucial is that there's no panic in the syntect library but an error so that the viewing program doesn't crash.

**Comment by keith-hall** [comment]
> What's crucial is that there's no panic in the syntect library but an error so that the program doesn't crash.

https://github.com/trishume/syntect/issues/98#issuecomment-1007898832
