### ISSUE TITLE
FLTK use case

### ISSUE THREAD

**Issue by 1sra3l** [trishume/syntect#423]
Hi,
I am using [fltk-rs](https://crates.io/crates/fltk) to make a text editor for fun.
To perfom syntax highlighting in FLTK you must use something like:
```rs
//This struct just shows the fltk types so you don't have to look it up
struct fltk::text::StyleTableEntry {
    fltk::enums::Color,
    fltk::enums::Font,
    i32,
}
// And for each style you assign a `&str` letter `["A".."Z"]`
// you also make a vector of these styles to give the buffer `style_table_vector` is a `Vec<StyleTableEntry>`
editor.set_highlight_data(editor.style_buffer.clone(), style_table_vector);
// `editor` is some fltk::text::TextEditor
// `text` is the most recently changed text `&str`
match editor.style_buffer() {
    Some(mut buf) => buff.append(&"A".repeat(text.len())
    None =>(),
} 
```
You offer bindings for terminals, etc, but I am unsure how to approach using your library, or if it is possible.

If this is already possible via your APIs, I was unsure what to search for to find my use case.

**Comment by Enselic** [comment]
Thank you for your interest in syntect.

> You offer bindings for terminals

Not sure what you mean by this. syntect can be used e.g. for HTML output. See https://github.com/trishume/syntect/blob/master/examples/synhtml.rs. So it can probably be used with fltk-rs too somehow. If it can't, it would be helpful if you elaborate on why it can't. (I'm afraid I don't have time to figure it out for you.)

**Comment by 1sra3l** [comment]
Sorry I did not choose my words better.  I meant you have a function for turning it into 24 bit terminal escape codes.
I found a different library to use a few months ago since I had no response from you, but thank you for taking the time to get back in contact.
the HTML output would not work for what I am using, FLTK uses a style table similar to what I describe above:
Code to highlight:
```rs
fn example() {
    // test
}
```
styletable:
```
BBACCCCCCCAAAA
AAAAEEEEEEE
A
```
Sorry I was not clear when I was explaining it the first time.
I am going to close this, since I found another library, but if you want to explain how to produce the styletable, in case anyone is looking for this, I could test it if you need me to.
