### ISSUE TITLE
We are ready to `cargo publish` v5.0.0

### ISSUE THREAD

**Issue by Enselic** [trishume/syntect#433]
@trishume The current master branch should be releasable as **v5.0.0**. We just need to update the date of the `CHANGELOG.md` entry for **v5.0.0** to the date of the release. If you are busy, I can take care of making the release, if you wish.

Here is current master branch of `syntect` passing all `bat` regression tests, including syntax highlighting regression tests for hundreds of languages: https://github.com/Enselic/bat/pull/85/checks

**Comment by trishume** [comment]
Sweet thanks so much for the work on this! I should hopefully have some time sometime between now and Sunday evening.

**Comment by trishume** [comment]
NVM realized that while I'm traveling I don't have the computer which has my personal Rust and crates.io setup on it. So I won't get to this until at least Tuesday.

**Comment by trishume** [comment]
Done! Thanks so much for all your work on this @Enselic!

https://github.com/trishume/syntect/releases/tag/v5.0.0
