### ISSUE TITLE
Question: Any interest in bundling simple CLI app for terminal/HTML highlighting?

### ISSUE THREAD

**Issue by stelcodes** [trishume/syntect#434]
Hi there, I tried searching for this question in the past issues but I couldn't find anything. Is there any interest in including a CLI app so Syntect can be used as a binary executable for ouputting HTML fragments like Pygments or Chroma? I don't see any projects in the "Projects using Syntect" section that do this specifically. If that's outside the scope of this project I would be happy to create one on my own. Perhaps this already exists and I'm just not aware.

I think it would be cool to replicate Chroma's CLI app's interface in particular as it's much cleaner than Pygments' in my opinion.

**Comment by keith-hall** [comment]
Hi, thanks for your interest. `syntect` is primarily designed to be a library. We have an example, `synhtml`, which can output html fragments, but I believe a full fledged CLI app is out of scope for this repo - you'd need to manage custom syntax definitions, color schemes etc. The `bat` project does this for pretty printing to the terminal.

**Comment by stelcodes** [comment]
@keith-hall Thank you for the response, I'll see if `bat` is willing to include HTML fragment output and if not I'll make my own CLI app. Actually that seems like a great intro to Rust exercise.
