### ISSUE TITLE
fancy-regex is outdated.

### ISSUE THREAD

**Issue by baehyunsol** [trishume/syntect#454]
The newest version of [fancy-regex](https://github.com/fancy-regex/fancy-regex) is 0.10.0, but syntect uses 0.7.0. Is there any reason using the outdated version?

**Comment by keith-hall** [comment]
No reason, just no dependabot to remind us and we didn't think of it. 0.10.0 would be good to upgrade to, it adds support for `\G` which some older syntax definitions still use.
