### ISSUE TITLE
The "name" key should be optional in "sublime-syntax" files

### ISSUE THREAD

**Issue by keith-hall** [trishume/syntect#46]
In syntect, trying to parse a `sublime-syntax` file without a `name` top level key causes a panic:

> thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ParseSyntax(MissingMandatoryKey("name"))'

But in Sublime Text, this key is optional (indeed, the "new syntax" template in ST doesn't contain a placeholder for it), so currently syntect cannot parse some valid syntaxes. If it is not provided, ST derives the name of the syntax from the filename - i.e. "Hello World.sublime-syntax" would have a name of "Hello World".

**Comment by trishume** [comment]
Ok interesting I didn't know that. 

Is there anything this is breaking right now? If not I'll probably work on the bugs in parsing found by the syntax tests first.

**Comment by keith-hall** [comment]
No no, this is definitely not urgent :) it just prevents me from running syntax tests against some third party syntaxes, nothing major :)

**Comment by FichteFoll** [comment]
Just wanted to note that I was trying to run CI tests using syntect for my PackageDev third-party package and am bothered by this issue. You can read more about this here: https://github.com/SublimeText/PackageDev/issues/98

**Comment by trishume** [comment]
I just pushed `v1.3.0` to crates.io with the fix for this. Release notes are on the Github releases page.

**Comment by FichteFoll** [comment]
Thanks. You possibly want to keep this issue open because it doesn't do The Right Thing atm, but I don't know if there is anything that depends on a syntax's name to be honest.
