### ISSUE TITLE
release with bumped `regex-syntax`

### ISSUE THREAD

**Issue by extrawurst** [trishume/syntect#486]
the last release has been a long time ago. right now `syntect` holds on to some pretty old versions of dependencies and a release from master which already bumped `regex-syntax` would be a great start

**Comment by Enselic** [comment]
Yep a new release will be made soonish, possibly next week

**Comment by Enselic** [comment]
[Done!](https://crates.io/crates/syntect/5.1.0)

**Comment by extrawurst** [comment]
Thank you!

**Comment by extrawurst** [comment]
@Enselic since #490 is merged it would be nice to release another one ❤️
