### ISSUE TITLE
HTML output doesn't include alpha channel

### ISSUE THREAD

**Issue by keith-hall** [trishume/syntect#50]
Is it intentional that in [the `styles_to_coloured_html` method of `src/html.rs` that the alpha channel of the color scheme is ignored](https://github.com/trishume/syntect/blob/8ea39449b07d4e97cb2778041038e22e4b81cf76/src/html.rs#L175-L178)?

It's use probably isn't that common, but I use it in my theme quite a bit (at least for background colors) and I suspect others do too - especially for languages embedded in other languages, like CSS and JS inside HTML documents.

**Comment by trishume** [comment]
Nope, unintentional. I probably just forgot it existed. Definitely a bug.
