### ISSUE TITLE
adding Nushell's syntax

### ISSUE THREAD

**Issue by cablehead** [trishume/syntect#524]
Hi!

How are new syntaxes added to the syntect crate?

It'd be great to have Nushell’s syntax available. @kurokirasama has a definition here: https://github.com/kurokirasama/nushell_sublime_syntax/blob/main/nushell.sublime-syntax

I'm curious if the mechanism that includes syntax definitions can source the definition directly from [nushell_sublime_syntax](https://github.com/kurokirasama/nushell_sublime_syntax), so updates are picked up automatically?

**Comment by keith-hall** [comment]
https://github.com/trishume/syntect/issues/523#issuecomment-1989323162

> I'm curious if the mechanism that includes syntax definitions can source the definition directly from [nushell_sublime_syntax](https://github.com/kurokirasama/nushell_sublime_syntax), so updates are picked up automatically?

typically syntaxes are included as git submodules, so dependabot can easily create PRs to bump them automatically

**Comment by cablehead** [comment]
Thanks for the info! 🙏🏻 I still can't work out the mechanic to include a new syntax. e.g. if I search the syntect repo for erlang, I don't find anything...

**Comment by keith-hall** [comment]
did you checkout submodules? Erlang is in `testdata/Packages/Erlang`

**Comment by cablehead** [comment]
would it be reasonable to add https://github.com/kurokirasama/nushell_sublime_syntax as an additional submodule, perhaps to: testdata/MoarPackages, and to update the build to load syntax from testdata/Packages + testdata/MoarPackages? .. or something roughly along those lines?

**Comment by keith-hall** [comment]
It may be reasonable, but I'm not yet convinced it's something we want in `syntect` as then we'll open the floodgates for requests for getting all sorts of packages added to `syntect` by default. (see https://github.com/trishume/syntect/issues/523#issuecomment-1989323162 for example.) Please help me to understand for what reason do you want it in this repository as opposed to in your consumer codebase?

**Comment by cablehead** [comment]
> I'm not yet convinced it's something we want in syntect as then we'll open the floodgates for requests for getting all sorts of packages added to syntect by default.

Ah gotcha. Yeah, that would quickly become impractical.

> Please help me to understand for what reason do you want it in this repository as opposed to in your consumer codebase?

Right, I don't think I've been appreciating how straightforward it would be to just add the nushell schema to my [consumer codebase](https://github.com/cablehead/stacks?tab=readme-ov-file#built-with). Beyond my own immediate use case, my motivation to have the schema included upstream is to help the nushell project become more mainstream, tooling-wise.

My understanding is now approaching: I believe the best way to do is: submit the schema to [sublimehq/Packages](https://github.com/sublimehq/Packages), which gets the nushell syntax into the most hands, if its genuinely broadly appealing, and reduces noise for downstream projects like syntect.

What are your thoughts, Keith?
