### ISSUE TITLE
Update to newer version of sublimehq/Packages

### ISSUE THREAD

**Issue by fgelm01** [trishume/syntect#527]
Would it be possible to update to update the `testdata/Packages` submodule to a newer version of https://github.com/sublimehq/Packages ?

It seems like the one that is there is about 7 years old.

My use case involves highlighting some C++20, and it is strange to not have the keywords `requires`, `concept`, and `co_await` not highlighted.

**Comment by keith-hall** [comment]
Unfortunately, no, this is not possible - more recent commits start using `.sublime-syntax` features that `syntect` doesn't support yet. https://github.com/trishume/syntect/issues/460
There's nothing to stop you from using a custom set of syntaxes though - i.e. with some patches applied on top. https://github.com/trishume/syntect/issues/168 may be of interest.

**Comment by fgelm01** [comment]
I see. Thank you for explaining.
