### ISSUE TITLE
Java syntax definition gets confused by Foo.class

### ISSUE THREAD

**Issue by robinst** [trishume/syntect#54]
With the following Java source:

```java
public class Test {

    void test1() {
        Foo.class;
    }

    void test2() {
    }
}
```

Syntect (8ea39449b07d4e97cb2778041038e22e4b81cf76) gets confused by the `Foo.class` line. All the source code after that line is incorrectly/not highlighted. Removing the line fixes it. It also happens when the `Foo.class` is part of an expression (e.g. used as an argument).

This may be related to #51, but I wasn't sure. (And it doesn't hurt to have another issue.)

**Comment by keith-hall** [comment]
It looks like a bug in the Java syntax definition that has since been fixed on the Default Packages repo. @trishume maybe it makes sense to update the submodules more often, what do you think?

**Comment by keith-hall** [comment]
Oh I beg your pardon, it looks like the Java syntax definition has actually been updated to include this bug on the Default Packages repo. I'll see if I can create a PR there to fix it ;)

**Comment by keith-hall** [comment]
https://github.com/sublimehq/Packages/pull/858

**Comment by robinst** [comment]
Nice, the upstream PR has been merged! Can we update the default packdump in syntect to get the fix?

**Comment by trishume** [comment]
I'll try to get around to updating it tonight.

**Comment by trishume** [comment]
So I tried updating to the latest version of the Sublime packages and unfortunately it seems the new Markdown syntax exhibits catastrophic backtracking on the regex I pasted below. Normally I would try and add some atomic capture groups, but I don't ever trust myself to understand this regex enough to do that without breaking it. It takes forever (I haven't bothered waiting more than a few minutes) to highlight even short lines.

I'm not sure how to handle the tradeoff between losing Markdown support completely but gaining all the fixes @keith-hall has made since I last updated.

I'm not sure I'll have the time to completely port to `fancy-regex` in the near-future to fix catastrophic backtracking, so I'm not sure what to do. Thoughts?

One option is that I fork the Sublime packages repo, revert markdown in my fork, and then base syntect off of that for now.

<details>
<summary>The Regex that does all the work in the new Markdown syntax</summary><p>

```regex
(?x)^
(?=  (?:[ ]{,3}>(?:.|$))
|    (?:[ ]{4}|\t)(?!$)
|    (?:[#]{1,6}\s*)
|    (?x:
    [ ]{,3}
    (?:
            [-](?:[ ]{,2}[-]){2,}
        |   [*](?:[ ]{,2}[*]){2,}
        |   [_](?:[ ]{,2}[_]){2,}
    )
    [ \t]*$
)
|    (?x:
    (?:(?x:
  (?:
    (?x:
  (?:
      \\[-`*_#+.!(){}\[\]\\>|]+                  # escape characters
  |   [^\[\]`\\]+                  # anything that isn't a square bracket or a backtick or the start of an escape character
  |   (?x:
    (`{4})(?=\S)[^`]+(?:[^`]+|(?!`{4})`*)*(`{4})(?!`)
|   (`{3})(?=\S)[^`]+(?:[^`]+|(?!`{3})`*)*(`{3})(?!`)
|   (`{2})(?=\S)[^`]+(?:[^`]+|(?!`{2})`*)*(`{2})(?!`)
|   (`{1})(?=\S)[^`]+(?:[^`]+|(?!`{1})`*)*(`{1})(?!`)
)                # inline code
  )
)
  | \[(?:                       # nested square brackets (one level deep)
        [^\[\]`]+               #  anything that isn't a square bracket or a backtick
        (?x:
    (`{4})(?=\S)[^`]+(?:[^`]+|(?!`{4})`*)*(`{4})(?!`)
|   (`{3})(?=\S)[^`]+(?:[^`]+|(?!`{3})`*)*(`{3})(?!`)
|   (`{2})(?=\S)[^`]+(?:[^`]+|(?!`{2})`*)*(`{2})(?!`)
|   (`{1})(?=\S)[^`]+(?:[^`]+|(?!`{1})`*)*(`{1})(?!`)
)?          #  balanced backticks
      )*\]                      #  closing square bracket
  )+                            # at least one character
)*\|){2}       # at least 2 non-escaped pipe chars on the line
|   (?!\s+\|)(?x:
  (?:
    (?x:
  (?:
      \\[-`*_#+.!(){}\[\]\\>|]+                  # escape characters
  |   [^\[\]`\\]+                  # anything that isn't a square bracket or a backtick or the start of an escape character
  |   (?x:
    (`{4})(?=\S)[^`]+(?:[^`]+|(?!`{4})`*)*(`{4})(?!`)
|   (`{3})(?=\S)[^`]+(?:[^`]+|(?!`{3})`*)*(`{3})(?!`)
|   (`{2})(?=\S)[^`]+(?:[^`]+|(?!`{2})`*)*(`{2})(?!`)
|   (`{1})(?=\S)[^`]+(?:[^`]+|(?!`{1})`*)*(`{1})(?!`)
)                # inline code
  )
)
  | \[(?:                       # nested square brackets (one level deep)
        [^\[\]`]+               #  anything that isn't a square bracket or a backtick
        (?x:
    (`{4})(?=\S)[^`]+(?:[^`]+|(?!`{4})`*)*(`{4})(?!`)
|   (`{3})(?=\S)[^`]+(?:[^`]+|(?!`{3})`*)*(`{3})(?!`)
|   (`{2})(?=\S)[^`]+(?:[^`]+|(?!`{2})`*)*(`{2})(?!`)
|   (`{1})(?=\S)[^`]+(?:[^`]+|(?!`{1})`*)*(`{1})(?!`)
)?          #  balanced backticks
      )*\]                      #  closing square bracket
  )+                            # at least one character
)+\|(?!\s+$)(?x:
  (?:
    (?x:
  (?:
      \\[-`*_#+.!(){}\[\]\\>|]+                  # escape characters
  |   [^\[\]`\\]+                  # anything that isn't a square bracket or a backtick or the start of an escape character
  |   (?x:
    (`{4})(?=\S)[^`]+(?:[^`]+|(?!`{4})`*)*(`{4})(?!`)
|   (`{3})(?=\S)[^`]+(?:[^`]+|(?!`{3})`*)*(`{3})(?!`)
|   (`{2})(?=\S)[^`]+(?:[^`]+|(?!`{2})`*)*(`{2})(?!`)
|   (`{1})(?=\S)[^`]+(?:[^`]+|(?!`{1})`*)*(`{1})(?!`)
)                # inline code
  )
)
  | \[(?:                       # nested square brackets (one level deep)
        [^\[\]`]+               #  anything that isn't a square bracket or a backtick
        (?x:
    (`{4})(?=\S)[^`]+(?:[^`]+|(?!`{4})`*)*(`{4})(?!`)
|   (`{3})(?=\S)[^`]+(?:[^`]+|(?!`{3})`*)*(`{3})(?!`)
|   (`{2})(?=\S)[^`]+(?:[^`]+|(?!`{2})`*)*(`{2})(?!`)
|   (`{1})(?=\S)[^`]+(?:[^`]+|(?!`{1})`*)*(`{1})(?!`)
)?          #  balanced backticks
      )*\]                      #  closing square bracket
  )+                            # at least one character
)+
)
)
```

</p>
</details>

**Comment by trishume** [comment]
Actually I've created a WIP PR for this issue, please discuss in #56 @keith-hall @robinst

**Comment by trishume** [comment]
Should be fixed by #56

**Comment by trishume** [comment]
I just pushed `v1.3.0` to crates.io with the fix for this. Release notes are on the Github releases page.

**Comment by robinst** [comment]
Awesome work, thanks @trishume and @keith-hall!
