### ISSUE TITLE
Add support for luau

### ISSUE THREAD

**Issue by 0xJWLabs** [trishume/syntect#546]
Can someone add support for luau (superset of lua) language? Thanks!

**Comment by keith-hall** [comment]
`syntect` is just a library, which happens to come with some language syntax support by default (which is unlikely to change much), but there's nothing to stop users of the library from using whatever languages they want... The only hit on package control at the moment for `luau` is a linter, so if the standard Lua highlighting isn't good enough, you'd likely need to extend it yourself with rules specific to luau.
