### ISSUE TITLE
Markdown syntax test failure investigation

### ISSUE THREAD

**Issue by keith-hall** [trishume/syntect#62]
Although the Markdown syntax tests pass on Sublime Text build 3126, it is currently failing in `syntect` because `syntect` doesn't suffer from this bug: https://github.com/SublimeTextIssues/Core/issues/1190

Therefore, in `syntect`, https://github.com/trishume/Packages/blob/537d1bfa5bc205aa461b12eb3c996935e017e575/Markdown/Markdown.sublime-syntax#L758 is popping immediately after the push. As it is not a bug in `syntect`, and the aforementioned bug will be fixed in the next ST build, it can definitely be considered a bug in the syntax definition, which will need a tweak to continue working as expected.

The test line in question is:

    - `code` - <a name="demo"></a>
    |          ^^^^^^^^^^^^^^^^^^^ meta.tag.inline.a.html

**Comment by trishume** [comment]
Interesting. I remember running into the problem where Sublime would avoid following infinite push/pop cycles. I implemented that I think by keeping track of a set of contexts already attempted at a position, but it seems Sublime just implemented it by saying "if you push and then pop at the same position, it must be a cycle".

**Comment by keith-hall** [comment]
Yeah ST's method was lazy ;) no idea what their new implementation will be though.

Anyway, my PR to the ST Default Packages repo with a fix for this has been merged, so we could choose to update https://github.com/trishume/Packages also :)
(There have also been a number of recent improvements to the Rust syntax definition, from what I can see.)

**Comment by keith-hall** [comment]
This is now passing all tests:

> Testing file testdata/Packages/Markdown/syntax_test_markdown.md
The test file references syntax definition file: Packages/Markdown/Markdown.sublime-syntax
Ok(Success(5119))
Testing file testdata/Packages/Markdown/syntax_test_multimarkdown.md
The test file references syntax definition file: Packages/Markdown/MultiMarkdown.sublime-syntax
Ok(Success(120))
