### ISSUE TITLE
Parsing C# file (RegexCharClass.cs) doesn't finish

### ISSUE THREAD

**Issue by robinst** [trishume/syntect#63]
The [RegexCharClass.cs from the MonoDevelop sources](https://github.com/mono/monodevelop/blob/522676ea6126e743df6b108a194dc155f4e8519e/main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Editor.Highlighting/RegexEngine/RegexCharClass.cs) takes a very long time to parse (killed it after a couple of minutes), with current master (f03fa0f672ab0a25ec93cddba11a8a6b036605f9):

    curl -LO "https://github.com/mono/monodevelop/raw/522676ea6126e743df6b108a194dc155f4e8519e/main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Editor.Highlighting/RegexEngine/RegexCharClass.cs"

    cargo build --release --example syncat

    time ./target/release/examples/syncat RegexCharClass.cs

**Comment by trishume** [comment]
This is probably also more catastrophic backtracking.

I should really look into Oniguruma options to bail out on bad cases.

**Comment by robinst** [comment]
Looks like the lines with a lot of `\u1234` escapes are the problem: https://github.com/mono/monodevelop/blob/522676ea6126e743df6b108a194dc155f4e8519e/main/src/core/MonoDevelop.Ide/MonoDevelop.Ide.Editor.Highlighting/RegexEngine/RegexCharClass.cs#L210

**Comment by robinst** [comment]
This PR should fix it by changing `\\u\h{,4}` to `\\u\h{4}` (which is also in line with the spec): https://github.com/sublimehq/Packages/pull/1132

**Comment by robinst** [comment]
Ah, this has been fixed by the change in Packages. Forgot to close the issue :).
