### ISSUE TITLE
add syntax highlighting for Vala

### ISSUE THREAD

**Issue by eyelash** [trishume/syntect#67]
It would be nice if the [Vala programming language](https://en.wikipedia.org/wiki/Vala_%28programming_language%29) was supported by default. There is a .tmLanguage [here](https://github.com/technosophos/Vala-TMBundle). Does syntect support .tmLanguage files or only .sublime-syntax files? If only the latter are supported I guess the .tmLanguage for Vala could easily be converted.

**Comment by Enselic** [comment]
This issue can be closed with motivation:

No more third party syntaxes will be added to this repo. Source: https://github.com/trishume/syntect/issues/373#issuecomment-929490843
