### ISSUE TITLE
Split syntect into multiple crates

### ISSUE THREAD

**Issue by cmyr** [trishume/syntect#68]
As we've been discussing [here](https://github.com/google/xi-editor/issues/284#issuecomment-301529194), It would be helpful for Xi if the parsing and the theme application components of syntect were available as separate crates.

Q: Might it make sense to also separate the `syntax_definition` module into a crate? It could be nice to take advantage of the syntax detection features it offers, instead of rolling our own.

I'm happy to take a stab at this work at some point, but would appreciate any preliminary guidance. Is this mostly a matter of turning the `highlighting` module into a crate? Any additional foreseeable challenges?

**Comment by trishume** [comment]
Yah it is mostly just turning the `highlighting` module into a crate, and moving the `scope.rs` out of parsing and into `highlighting` before doing so.

**Comment by cmyr** [comment]
okay, so thinking about how to structure this in repo, tell me how this sounds?

1. new top level directory, `highlighting`, which contains the `syntect-highlighting` crate. So src in `highlighting/src`, cargo.toml at `highlighting/cargo.toml`. 

2. add `syntect-highlighting` as a dep of `syntect`. (Do I need to manually exclude the `highlighting` directory in `syntect/cargo.toml`?)

Then...

3. Update docs as needed

4. PR, get @trishume to publish to crates.io


I'm finding this work oddly intimidating, but I've been having a bit of a slow week. Anyway, let me know if you have any additional thoughts?

**Comment by cmyr** [comment]
also maybe there is a better name than `highlighting`. Maybe `syntect-core`? `syntect-common`?

**Comment by trishume** [comment]
That plan looks good, you can look at `xi-editor` as an example of how to do multiple crates in one repo.

I think `highlighting` is fine, since that's mostly what it does, and some data structures based around doing that. Potentially `themeing` might be better in that it more explicitly excludes the parsing part, but I'm not sure about it.
