### ISSUE TITLE
Naming confusion in ThemeSettings

### ISSUE THREAD

**Issue by cmyr** [trishume/syntect#80]
Comparing the documentation of `ThemeSettings` in `theme.rs`, and comparing that with the sublimetext documentation [here](https://www.sublimetext.com/docs/3/color_schemes.html#global_settings), I'm confused in a few places.

1. the ST docs describe `selection` and `selectionForeground` properties. The syntect docs describe `selection` and `selectionBackground`. In the actual `InspiredGitHub` theme, as loaded by syntect, `selection` has a value but `selectionBackground` is missing. This is surprising to me: I would expect that the background is more likely to be present than the foreground?

2. Less significantly there are a few fields missing. None of these are critical (to me), but among the missing are `inactiveSelectionForeground`.

3. There are some items for which the syntect docs are either unclear (`foreground`, `selection`) or have errors (`find_highlight_foreground`).

@trishume if you have anything to add here let me know, especially around item 1; then I'll PR as appropriate.

**Comment by trishume** [comment]
I know little to nothing about this because the theme loading is the one part of syntect that I straight-up copy-pasted from https://github.com/defuz/sublimate

It's possible its wrong.

**Comment by cmyr** [comment]
Okay, will investigate.
