### ISSUE TITLE
good place to mention HTTP server?

### ISSUE THREAD

**Issue by slimsag** [trishume/syntect#95]
Feel free to close this issue if this is the wrong place to ask/mention this!

I had the requirement of using Syntect from another language (Go) so I chose to communicate with Syntect via an HTTP server (rocket.rs). While doing this, I ran into various issues as a Rust beginner and came across threads like https://github.com/trishume/syntect/issues/20 and it seems like others have had the same idea (exposing Syntect via HTTP) but I didn't successfully find any open source version of this. I ended up creating:

https://github.com/sourcegraph/syntect_server

I figured the least I could do is post on this issue tracker for future people like myself in the future to hopefully run across this, as it may help them.

I also wanted to ask if you would accept a PR to add a "Projects using Syntect" section to the README (or somewhere else if you prefer) since I think that would be useful for folks looking for an HTTP-server variant, and also for beginners like myself to understand usage of Syntect? I can send this if you agree :)

**Comment by trishume** [comment]
Cool! I'd accept a PR that added a section like that to the Readme.

I'd also encourage you to look into writing some Rust to expose `syntect` as a C library, and then use that with CGo, but I understand that lots of Go users avoid CGo for a variety of reasons.

**Comment by slimsag** [comment]
Awesome! I'll send that sometime tomorrow.

> I'd also encourage you to look into writing some Rust to expose syntect as a C library, and then use that with CGo, but I understand that lots of Go users avoid CGo for a variety of reasons.

I have very extensive experience working with CGO, actually, but in this case an HTTP server fit my needs much better (and I figured other languages could easily use this to add e.g. syntax highlighting to blogs, etc). Also, deploying CGO applications is not as fun compared to regular Go applications (need a C compiler installed, etc).
